# Install a centos7

FROM daocloud.io/centos:7
MAINTAINER dwl

ENV PATH=$PATH:/usr/local/bin:/usr/pbin:/usr/psbin:/phome

#RUN echo "" >> /etc/mongodb.conf

CMD ["/usr/bin/mongod", "--config", "/etc/mongodb.conf"]